### ISSUE TITLE
Simplify CNS search domain for consumers

### ISSUE THREAD

**Issue by jwreagor** [autopilotpattern/mysql#103]
Currently the `$TRITON_CNS_SEARCH_DOMAIN_PRIVATE` variable needs to be filled in by the user but we automatically generate this for the user in the Consul blueprint. Let's port this over.

I have a small patch for this but I'm still testing.

**Comment by misterbisson** [comment]
This _should_ be set correctly [in `triton-compose` and `triton-docker` here](https://github.com/joyent/triton-docker-cli/blob/master/triton-docker#L121). It's intended not to stomp on existing env vars, just set them if they don't exist, and that's really important for any usage that's not on Triton public cloud.

**Comment by jwreagor** [comment]
Ok that wasn’t expected, I guess my triton-docker is missing that functionality.

**Comment by misterbisson** [comment]
We need an update mechanism there, I ticketed that in https://github.com/joyent/triton-docker-cli/issues/20

**Comment by jwreagor** [comment]
Going to close this since upgrading the `triton-docker-cli` tool worked fine.
