### ISSUE TITLE
TRITON_MYSQL_CONSUL vs CONSUL as environment variable in triton-mysql.py

### ISSUE THREAD

**Issue by roXet** [autopilotpattern/mysql#11]
Should the default environment varible for consul be TRITON_MYSQL_CONSUL here?
https://github.com/autopilotpattern/mysql/blob/master/bin/triton-mysql.py#L35

Seems like using simply 'CONSUL' here will make it easier to line up with other services in a single compose project, especially when running on Triton using CNS.

**Comment by misterbisson** [comment]
That's a good question that goes with https://github.com/autopilotpattern/mysql/pull/10 and further cleanup proposed by https://github.com/autopilotpattern/mysql/issues/12. 

@tgross might be able to answer whether or not he had a special reason for the var name, or if he was namespacing it out of habit.

**Comment by tgross** [comment]
Yeah, I don't think there was any particular name and I agree that having it just be `CONSUL` would be better.

**Comment by misterbisson** [comment]
Fixed in https://github.com/autopilotpattern/mysql/pull/14
