### ISSUE TITLE
Optimize Dockerfile/image size

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/mysql#18]
I believe the following portion of the `Dockerfile` can be combined into a single `RUN` statement that removes `gcc` and `python-dev` after doing the `pip install`, similarly to https://github.com/autopilotpattern/nfsserver/blob/wip/Dockerfile#L8-L19 .

```
RUN apt-get update \
    && apt-get install -y \
        python \
        python-dev \
        gcc \
        curl \
        percona-xtrabackup \
    && rm -rf /var/lib/apt/lists/*

# get Python drivers MySQL, Consul, and Manta
RUN curl -Ls -o get-pip.py https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    pip install \
        PyMySQL==0.6.7 \
        python-Consul==0.4.7 \
        manta==2.5.0
```

**Comment by tgross** [comment]
Released in https://github.com/autopilotpattern/mysql/releases/tag/5.6r2.2.0
