### ISSUE TITLE
Update Compose files to 2.0 format

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/mysql#19]
https://github.com/autopilotpattern/mysql/pull/9 demonstrated Docker Compose format 2.0 for compatibility with Docker Swarm, but https://github.com/autopilotpattern/mysql/pull/14 made changes that conflict with #9.

New plan:
- Update `docker-compose.yml` and `local-compose.yml` to the 2.0 format
- `local-compose.yml` extends `docker-compose.yml`
- Use `network_mode: bridge` in `docker-compose.yml`

`docker-compose.yml` will work on Triton, `local-compose.yml` will work in local Docker and Swarm environments. After the completion of https://smartos.org/bugview/DOCKER-723 and related tickets, we can drop `network_mode: bridge` from `docker-compose.yml`.

**Comment by tianon** [comment]
Sounds like a sane plan! :+1:

**Comment by tgross** [comment]
This will be covered in https://github.com/autopilotpattern/mysql/pull/79 because I needed it for https://github.com/autopilotpattern/mysql/issues/51 and getting the builds running on Jenkins.

**Comment by tgross** [comment]
Merged in https://github.com/autopilotpattern/mysql/pull/79

**Comment by tgross** [comment]
Released in https://github.com/autopilotpattern/mysql/releases/tag/5.6r3.1.2
