### ISSUE TITLE
Replicas fail to initialise

### ISSUE THREAD

**Issue by lguminski** [autopilotpattern/mysql#22]
When many containers start at the same time, there is no backup yet (the freshly elected master hasn't created one yet), so replicas fail to initialise their databases, and never recover from the state.

**Comment by tgross** [comment]
@lguminski this is currently a design limitation. The leader election process happens in the health check, and we can't restore the snapshot once `mysqld` is running so it has to happen in the `preStart`. We might be able to change this by forcing a replica to poll/wait during `preStart` if a primary has been elected but there's no backup yet.

**Comment by tgross** [comment]
Closing in lieu of https://github.com/autopilotpattern/mysql/issues/29
