### ISSUE TITLE
Replicas did not reconnect

### ISSUE THREAD

**Issue by lguminski** [autopilotpattern/mysql#23]
This could be a Consul issue, but I noticed that after leader re-election, there is "mysql-primary" service in Consul Web UI, but the following code (`bin/triton-mysql.py`)

    nodes = consul.health.service(PRIMARY_KEY, passing=True)[1]

kept returning an empty set. This way replicas could not connect to master.

**Comment by tgross** [comment]
@lguminski do you have any logs for this? There's not really enough to go on and replicate this here.

**Comment by tgross** [comment]
Without logs I'm going to have to close this issue. Please open if you are able to get some more information for us.
