### ISSUE TITLE
Improve docs around Manta keys

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/mysql#5]
# MANTA_KEY_ID

`MANTA_KEY_ID` _must_ be the md5 formatted key fingerprint. A SHA256 will result in errors.

This one-liner generates the correct fingerprint:

```bash
ssh-keygen -E md5 -lf <ssh key path> | awk '{print substr($2,5)}
```

# MANTA_PRIVATE_KEY

`MANTA_PRIVATE_KEY` must be the whole private key, not a path. I do not know of a way to put the whole, multi-line key into the `_env` file, but this will put it into the local environment:

```bash
export MANTA_PRIVATE_KEY=`cat ~/.ssh/id_rsa`
```

**Comment by tgross** [comment]
> MANTA_KEY_ID must be the md5 formatted key fingerprint. A SHA256 will result in errors.

Ah, yeah that's in the Joyent docs but should certainly be repeated here.

> I do not know of a way to put the whole, multi-line key into the _env file

As far as I can tell there isn't one, alas.

**Comment by tgross** [comment]
Adding a script that generates the env file and asserts that the working environment is correct would probably be a good addition to the blueprint, given the number of fiddly bits that need to be done before we do the "simple `docker-compose up`!"

**Comment by misterbisson** [comment]
@tgross tried a different approach in https://github.com/dekobon/triton-jenkins/blob/master/setup.sh#L121 that should maybe be implemented here as well

**Comment by misterbisson** [comment]
Fixed in https://github.com/autopilotpattern/mysql/pull/14
