### ISSUE TITLE
Implement leave_on_terminate for Consul co-process

### ISSUE THREAD

**Issue by misterbisson** [autopilotpattern/mysql#56]
Following from https://github.com/joyent/containerpilot/issues/218: When a Consul agent running as a co-process in a ContainerPiloted application exits, it is not de-registered from the Consul cluster.

@fitz123 suggests [the `leave_on_terminate` Consul option](https://www.consul.io/docs/agent/options.html#leave_on_terminate) will fix that. This ticket proposes implementing that option in this repo and for others in https://github.com/autopilotpattern.

**Comment by tgross** [comment]
N.B.
> On agents in client-mode, this defaults to true

So we really just need to upgrade to Consul 0.7.0 to get this.

**Comment by tgross** [comment]
Released in https://github.com/autopilotpattern/mysql/releases/tag/5.6r3.1.0
