### ISSUE TITLE
Add Percona Monitoring and Management to the cluster

### ISSUE THREAD

**Issue by neuroserve** [autopilotpattern/mysql#58]
To enhance the setup, it might be a good idea to add Percona monitoring and management:
https://www.percona.com/doc/percona-monitoring-and-management/index.html

It consists basically of two Docker containers and the pmm-client package, that needs to be installed and activated on the mysql servers. The pmm-server IP/name could be transferred via its cns name (similar to the consul name).

It delivers query analysis and a grafana based metrics monitor. The backend is prometheus.

**Comment by tgross** [comment]
@neuroserve in https://github.com/autopilotpattern/mysql/issues/16 we've got an open issue to implement telemetry by instrumenting with the Percona tools and then serving metrics via the ContainerPilot prometheus endpoint. I'm going to close this ticket as a dupe and move your suggestions into that issue for further discussion.
