### ISSUE TITLE
Consul 2 private interfaces

### ISSUE THREAD

**Issue by Smithx10** [autopilotpattern/mysql#80]
My Triton on premsis has a private ip range for both external and the fabric network.

Consul errors out when this situation occurs.  Is there any better way to boot strap this or handle the dynamic IP when binding?

Some people have used things like the following: 

"I don't know if it's the *best* way, but in my Vagrant cluster I have init files and something like BIND=`ifconfig eth2 | grep "inet addr" | awk '{ print substr($2,6) }'`. Then starting consul as a service."  

How can we handle this in Autopilot pattern?

**Comment by Smithx10** [comment]
Looks like the local consul-agent does the same 

2017/03/07 21:20:37 ==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.

**Comment by tgross** [comment]
You'll want to update the ContainerPilot `interfaces` config for the Consul service. This will get used by the `preStart` command to update the IP address you want to bind to: ref https://github.com/autopilotpattern/consul/blob/master/bin/consul-manage#L8
